feat: Add LinkedList & Node classes
RogerMo01/OOP-Exercises pull request #11
Opened 2020-09-26 02:30 UTC by RogerMo01

2020-11-01 15:35 UTC, LongJohnSilver1504 commented on OOP-Exercises/MyLinkedList.cs
> +        public void AddFirst(MyNode node)
Try to avoid names like MYN-Node, My-Class, My-.....,  **My** don't apport any information

2020-11-01 15:39 UTC, LongJohnSilver1504 commented on OOP-Exercises/MyLinkedList.cs
> +        public MyNode AddFirst(int value)
We have similar codes here try to DRY the code

2020-11-01 15:40 UTC, LongJohnSilver1504 commented on OOP-Exercises/MyLinkedList.cs
> +        public void AddLast(MyNode node)
We have similar logic here try to re-use some code

2020-11-01 15:45 UTC, LongJohnSilver1504 commented on OOP-Exercises/MyLinkedList.cs
> +            while (indexer != LastNode)
Be careful !!!!
By default, two non-record reference-type operands are equal if they refer to the same object:
``` C# 
public class ReferenceTypesEquality
{
    public class MyClass
    {
        private int id;

        public MyClass(int id) => this.id = id;
    }

    public static void Main()
    {
        var a = new MyClass(1);
        var b = new MyClass(1);
        var c = a;
        Console.WriteLine(a == b);  // output: False
        Console.WriteLine(a == c);  // output: True
    }
}
```
More info here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators

2020-11-01 15:46 UTC, LongJohnSilver1504 commented on OOP-Exercises/MyNode.cs
> +    public class MyNode
Change MyNode to Node or LinkedNode but I prefer the first option.

2020-11-01 15:48 UTC, LongJohnSilver1504 requested changes
Check the equality problem, after that you can solve it  if you override the equal operator:
https://docs.microsoft.com/en-us/dotnet/api/system.object.equals?view=netcore-3.1
Let me know if you have some doubts

2020-11-02 01:15 UTC, RogerMo01 commented on OOP-Exercises/MyLinkedList.cs
> +        public void AddFirst(MyNode node)
Done!

2020-11-02 01:19 UTC, RogerMo01 commented on OOP-Exercises/MyNode.cs
> +    public class MyNode
Done!

2020-11-02 01:47 UTC, RogerMo01 commented on OOP-Exercises/MyLinkedList.cs
> +        public MyNode AddFirst(int value)
Done!

2020-11-02 01:56 UTC, RogerMo01 commented on OOP-Exercises/MyLinkedList.cs
> +        public void AddLast(MyNode node)
Done!

2020-11-06 04:22 UTC, RogerMo01 commented on OOP-Exercises/MyLinkedList.cs
> +            while (indexer != LastNode)
Solved whit Equals override

2020-11-09 04:15 UTC, LongJohnSilver1504 approved these changes
Good work LGTM!.
@RogerMo01  Merge this PR

2020-11-09 05:29 UTC, merged