feat: Add ParenthesisValidation class
RogerMo01/OOP-Exercises pull request #12
Opened 2020-09-26 02:36 UTC by RogerMo01

2020-11-01 15:58 UTC, LongJohnSilver1504 commented on OOP-Exercises/ParenthesisValidation.cs
> +    class ParenthesisValidation
Good but  assume the string only has opened and closed parenthesis.

2020-11-01 15:58 UTC, LongJohnSilver1504 requested changes
Good but why ot static static class

2020-11-02 03:24 UTC, RogerMo01 commented on OOP-Exercises/ParenthesisValidation.cs
> +    class ParenthesisValidation
Done!

2020-11-09 04:18 UTC, LongJohnSilver1504 approved these changes
Good but remember commit convention:
instead:
Assume the string only has opened and closed pharentheses
fix: String only has opened and closed pharentheses
LGTM!

2020-11-09 13:56 UTC, merged