feat: Set class
RogerMo01/OOP-Exercises pull request #2
Opened 2020-09-02 02:51 UTC by RogerMo01

This is the Set class

2020-09-03 13:22 UTC, LongJohnSilver1504 commented on OOP-Exercises/Set.cs
> +        public int[] Sequence { get; private set; }
Why not  use list instead of array to avoid length problem

2020-09-03 13:23 UTC, LongJohnSilver1504 commented on OOP-Exercises/Set.cs
> +            if (Array.IndexOf(Sequence, element) >= 0)
Why not  return Array.IndexOf(Sequence, element) >= 0

2020-09-03 13:27 UTC, LongJohnSilver1504 commented on OOP-Exercises/Set.cs
> +            Array.Copy(Sequence, newSequence, Sequence.Length);
Using list we avoid this oparation

2020-09-03 13:28 UTC, LongJohnSilver1504 commented on OOP-Exercises/Set.cs
> +            if (Sequence == null)
using list we avoid asking for null

2020-09-03 13:28 UTC, LongJohnSilver1504 requested changes
Use List instead of array

2020-09-03 17:11 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +        public int[] Sequence { get; private set; }
Ok.

2020-09-03 17:15 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +            if (Array.IndexOf(Sequence, element) >= 0)
This will be unnecesary, if I use List<> instead Array, I will change this for the Count property of Lists

2020-09-03 17:21 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +            if (Sequence == null)
This will be unnecesary too. If I use Lists, this method can be deleted

2020-09-03 17:21 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +            Array.Copy(Sequence, newSequence, Sequence.Length);
Ok

2020-09-03 17:21 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +        public int[] Sequence { get; private set; }
Done!

2020-09-03 17:21 UTC, RogerMo01 commented on OOP-Exercises/Set.cs
> +            Array.Copy(Sequence, newSequence, Sequence.Length);
Done!

2020-09-04 16:25 UTC, LongJohnSilver1504 approved these changes
Good work LGTM!

2020-09-04 16:26 UTC, merged