feat: Employee class
RogerMo01/OOP-Exercises pull request #5
Opened 2020-09-04 02:46 UTC by RogerMo01

2020-09-04 02:48 UTC, RogerMo01 commented
What should I implement in al method called ToString() for this class??

2020-09-06 01:06 UTC, LongJohnSilver1504 requested changes
Good work, the toString method is for do 
Employee.toString() // and get something like   id-5 Roger Moreno with salary 1mn

2020-09-06 02:10 UTC, LongJohnSilver1504 commented on OOP-Exercises/Employee.cs
> +        public new string ToString => "Id-" + Id + " FirstName-" + FirstName + " LastName-" + LastName + " CurrentSalary-" + Salary;
Why not use string interpolation here

2020-09-06 02:17 UTC, RogerMo01 commented on OOP-Exercises/Employee.cs
> +        public new string ToString => "Id-" + Id + " FirstName-" + FirstName + " LastName-" + LastName + " CurrentSalary-" + Salary;
"Void" reason
Cleared Up!

2020-09-06 02:18 UTC, merged